# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: func_exec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='func_exec.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x66unc_exec.proto\",\n\x0bTaskRequest\x12\r\n\x05\x66name\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x01(\t\"\x1b\n\tTaskReply\x12\x0e\n\x06result\x18\x01 \x01(\t2X\n\x08\x46uncExec\x12%\n\x07GetTask\x12\x0c.TaskRequest\x1a\n.TaskReply\"\x00\x12%\n\x07RunExec\x12\x0c.TaskRequest\x1a\n.TaskReply\"\x00\x62\x06proto3')
)




_TASKREQUEST = _descriptor.Descriptor(
  name='TaskRequest',
  full_name='TaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fname', full_name='TaskRequest.fname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='TaskRequest.params', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=63,
)


_TASKREPLY = _descriptor.Descriptor(
  name='TaskReply',
  full_name='TaskReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='TaskReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['TaskRequest'] = _TASKREQUEST
DESCRIPTOR.message_types_by_name['TaskReply'] = _TASKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _TASKREQUEST,
  __module__ = 'func_exec_pb2'
  # @@protoc_insertion_point(class_scope:TaskRequest)
  ))
_sym_db.RegisterMessage(TaskRequest)

TaskReply = _reflection.GeneratedProtocolMessageType('TaskReply', (_message.Message,), dict(
  DESCRIPTOR = _TASKREPLY,
  __module__ = 'func_exec_pb2'
  # @@protoc_insertion_point(class_scope:TaskReply)
  ))
_sym_db.RegisterMessage(TaskReply)



_FUNCEXEC = _descriptor.ServiceDescriptor(
  name='FuncExec',
  full_name='FuncExec',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=94,
  serialized_end=182,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTask',
    full_name='FuncExec.GetTask',
    index=0,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASKREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RunExec',
    full_name='FuncExec.RunExec',
    index=1,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASKREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FUNCEXEC)

DESCRIPTOR.services_by_name['FuncExec'] = _FUNCEXEC

# @@protoc_insertion_point(module_scope)
